export const MESSAGE_FORM_UPDATE_VALUE = 'MESSAGE_FORM_UPDATE_DATA';
export const MESSAGE_FORM_SEND_FILE = 'MESSAGE_FORM_SEND_FILE';
export const MESSAGE_FORM_SUBMIT = 'MESSAGE_FORM_SUBMIT';

export const LOGIN_TRY = 'LOGIN_TRY';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_OK = 'LOGIN_OK';

export const GET_CHATS_LIST = 'GET_CHATS_LIST';
export const GET_USER_DATA = 'GET_USER_DATA';
