export const MESSAGE_FORM_UPDATE_VALUE = 'MESSAGE_FORM_UPDATE_DATA';
export const MESSAGE_FORM_SEND_FILE = 'MESSAGE_FORM_SEND_FILE';
export const MESSAGE_FORM_SUBMIT = 'MESSAGE_FORM_SUBMIT';

export const LOGIN_TRY = 'LOGIN_TRY';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_OK = 'LOGIN_OK';

export const GET_CHATS_LIST = 'GET_CHATS_LIST';
export const CHATS_LIST_LOADED = 'CHATS_LIST_LOADED';
export const CHATS_LIST_LOAD_FAIL = 'CHATS_LIST_LOAD_FAIL';
export const CHATS_LIST_NEW_CHAT = 'CHATS_LIST_NEW_CHAT';
export const CHATS_LIST_NEW_CHAT_OK = 'CHATS_LIST_NEW_CHAT_OK';

export const USER_DATA_LOADED = 'USER_DATA_LOADED';
export const USER_NEW = 'USER_NEW';
export const USER_NEW_OK = 'USER_NEW';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_OK = 'GET_MESSAGES_OK';

export const MESSAGE_DELIVERED = 'MESSAGE_DELIVERED';
export const MESSAGE_DELIVERY_FAIL = 'MESSAGE_DELIVERY_FAIL';

export const FILE_LOADED = 'FILE_LOADED';
